### ISSUE TITLE
Implement the best CI/CD practices to the application, isolating code in repositories, like:

### ISSUE THREAD

**Issue by marcos-dev88** [FIAP-SA-Hermes-Foods/fiap-hf-src#94]
1.  1 repository to Lambda;
2.  1 repository to infrastructure Kubernetes and Terraform;
3.  1 repository to database infrastructure managed by Terraform;
4.  1 repository to your application running through Kubernetes.

**Comment by leonrd0** [comment]
We forgot to close this issue :smile:

This matter was treated on our last release, in another words on the last phase from _Pos-Tech_
